name: "Test"

on:
  workflow_dispatch:
  release:
    types: [created]
    tags:
      - 'v*'


jobs:
  client-by-default:
    runs-on: ubuntu-Latest
    name: client warp+doh mode by default
    steps:
      - uses: OreosLab/warp-on-actions1@Latest

  client-ipv4:
    runs-on: ubuntu-Latest
    name: client warp+doh mode with ipv4
    steps:
      - name: Set up WARP with client with ipv4
        uses: OreosLab/warp-on-actions1@Latest
        with:
          mode: client
          stack: ipv4

  client-ipv6:
    runs-on: ubuntu-Latest
    name: client warp+doh mode with ipv6
    steps:
      - name: Set up WARP with client
        uses: OreosLab/warp-on-actions1@Latest
        with:
          mode: client
          stack: ipv6

  client-dual:
    runs-on: ubuntu-Latest
    name: client warp+doh mode with dual
    steps:
      - name: Set up WARP with client
        uses: OreosLab/warp-on-actions1@Latest
        with:
          mode: client
          stack: dual

  wireguard-ipv4:
    runs-on: ubuntu-Latest
    name: wireguard mode with ipv4
    steps:
      - name: Set up WARP with wireguard
        uses: OreosLab/warp-on-actions1@Latest
        with:
          mode: wireguard
          stack: ipv4

  wireguard-ipv6:
    runs-on: ubuntu-Latest
    name: wireguard mode with ipv6
    steps:
      - name: Set up WARP with wireguard
        uses: OreosLab/warp-on-actions1@Latest
        with:
          mode: wireguard
          stack: ipv6

  wireguard-dual:
    runs-on: ubuntu-Latest
    name: wireguard mode with dual
    steps:
      - name: Set up WARP with wireguard
        uses: OreosLab/warp-on-actions1@Latest
        with:
          mode: wireguard
          stack: dual
